const predefined_color = 51;
export default [
  {
    type: 'predefined_card_suit_space',
    message0: '黑桃',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_suit_club',
    message0: '梅花',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_suit_heart',
    message0: '红桃',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_suit_diamond',
    message0: '方块',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_suit_nosuit',
    message0: '无花色',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_color_black',
    message0: '黑色',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_color_red',
    message0: '红色',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_color_nocolor',
    message0: '无色',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_type_basic',
    message0: '基本',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_type_trick',
    message0: '锦囊',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_type_equip',
    message0: '装备',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_subtype_none',
    message0: '无子类型',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_subtype_delayedtrick',
    message0: '延时锦囊',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_subtype_weapon',
    message0: '武器',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_subtype_armor',
    message0: '防具',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_subtype_defensive_ride',
    message0: '防御坐骑',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_subtype_offensive_ride',
    message0: '进攻坐骑',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_subtype_treasure',
    message0: '宝物',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_unknown',
    message0: '未知区域',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_player_hand',
    message0: '手牌区',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_player_equip',
    message0: '装备区',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_player_judge',
    message0: '判定区',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_player_special',
    message0: '武将牌上/旁',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_processing',
    message0: '处理区',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_draw_pile',
    message0: '牌堆',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_discard_pile',
    message0: '弃牌堆',
    output: 'Number',
    colour: predefined_color,
  },
  {
    type: 'predefined_card_void',
    message0: '移出游戏区',
    output: 'Number',
    colour: predefined_color,
  },
];
